sudo: false
language: ruby
rvm:
  - 2.4.2
before_install: gem install bundler -v 1.15.4
env:
  global:
    secure: l4Pf93UaHAHqXZMeG581/jsVobnir5px7ml7e7foWoNVcpY1eieGAY34z8bcR+eF24xkWBDAUjb3I4vyu6DrYtdJkCz/EQIrcSPVT/lztcDzwf4fjOiFcOTe8JB5AyIU/3fwX94suqgQhabW9eNHlyUNaxAKXSBBT0euD3cUS40dGRMX73XB0HSH+xWXnQi2OBwppSbjF07kiOBL3MXKzW1RabIlCD677wLxXNPZSoK1MxxTDRmvidGsyo0V52ac8XdC/jpNMzIteOUv95k9HvuUl1RRd6687bNn2efxI8DsdtatHIH3N/+9wnUXucxORGYcoVz3D4k2uD35ULSodDyjE6VURgMQt0CLjDOjjQq/QtX4gB0B9A8Z7POYylHKotqlnZvgKMUZZqFITL0Mc9JNIup2GdZAYjGFvPQYQ7PADY1UFtiBVW5tBzapwIyEPMp2KVbeRR2+n4FEd5zqi4iY53eg7JgPRHzQaz8PuuIH+RwgoXjvD0IwPZLcCcceAAMWTixpTlHsCAdGk1V7YYWAsujNgLqQ+2Oy/USs5zovLovO2eRj1Mp4i8eUwRcz66jZfeQlssRhQwJXm1wrc5nRULsOQlr3/rg/0MNkwrk/OPL/oawcDRexUJ9QnKoC+hOeOeA/ZA7cc6xB9wqfL8mBxeUo5LXdMdwd7q0Uup4=
addons:
  apt:
    packages:
    - libhunspell-dev
